server:
  port: 10010
  servlet:
    context-path: /fastdevelop
spring:
  application:
    name: fastdevelop
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fastdevelop?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: Yhrh#2020
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

pagehelper:
  helper-dialect: mysql

fastdevelop:
  blog:
    detailMdPath: C:\Users\admin\Desktop\kelin\projects\blogMdPath\


encrypt:
  key-store:
    location: classpath:/fastdevelop.keystore #秘钥所在位置
    secret: fastdevelopkeystore # 秘钥secret
    alias: fastdevelopkey #秘钥别名
    password: fastdevelop #秘钥密码

auth:
  tokenValiditySeconds: 36000  #token存储到redis的过期时间
  clientId: fastdevelop
  clientSecret: 123456
  cookieDomain: localhost
  cookieMaxAge: 36000


#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
